runtime: nodejs18
env: flex

instance_class: F2

automatic_scaling:
  min_instances: 1
  max_instances: 10

handlers:
  - url: /static
    static_dir: client/build/static
  - url: /(.*)
    static_files: client/build/\1
    upload: client/build/(.*)
