steps:
  # Step 1: Install dependencies for Node.js
  - name: 'gcr.io/cloud-builders/npm'
    entrypoint: 'npm'
    args: ['install']
    dir: '.'  # This assumes your package.json is in the root directory

  # Step 2: Build the React application (client-side)
  - name: 'gcr.io/cloud-builders/npm'
    entrypoint: 'npm'
    args: ['run', 'build']
    dir: './client'  # If your React app is in the 'client' directory (adjust if needed)

  # Step 3: Install dependencies for Node.js backend
  - name: 'gcr.io/cloud-builders/npm'
    entrypoint: 'npm'
    args: ['install']
    dir: './server'  # Assuming your Node.js backend is in a 'server' folder (adjust if needed)

  # Step 4: Deploy to Google Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['run', 'deploy', 'fyp',  # 'my-app' is the name of your Cloud Run service
           '--image', 'gcr.io/$PROJECT_ID/fyp',  # Name of the container image to deploy
           '--platform', 'managed',
           '--region', 'us-central1',  # Change to your preferred region
           '--allow-unauthenticated']
    dir: '.'  # Ensure the command is executed from the root directory

images:
  - 'gcr.io/$PROJECT_ID/fyp'  # Container image name to push to Artifact Registry

timeout: 1200s  # Optional: Timeout for the build, adjust based on your project size
